{
 "title": "Aerospike Dashboard",
 "tags": [
  "aerospike",
  "graphite"
 ],
 "time": { "from": "now-30m", "to": "now-10s" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "${VAR_prefix}" },
   { "name": "cluster", "query": "$prefix.*" },
   { "name": "hostname", "query": "$prefix.$cluster.*" },
   { "name": "namespace", "query": "$prefix.$cluster.$hostname.*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "# Instructions\n\nThis dashboard is designed to be used in conjunction with \n[aerospike-graphite](https://github.com/aerospike/aerospike-graphite).\n\nThis dashboard shows comprehensive metrics across an entire cluster. \nAs such, the cluster layout must be encoded in the schema.\n\neg: aerospike.cluster.hostname... set by `asgraphite.py --prefix aerospike.cluster ...`\n\nThen, choose the cluster within the `cluster` parameter above, or select the specific nodes in\nthe `hostname` parameter."
  },
  { "title": "Overall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cluster Integrity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "minSeries($prefix.$cluster.$hostname.service.cluster_integrity)"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries($prefix.$cluster.$hostname.$namespace.stop_writes)"
    }
   ]
  },
  {
   "title": "HWM Breached",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries($prefix.$cluster.$hostname.$namespace.hwm_breached)"
    }
   ]
  },
  {
   "title": "System Swapping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries($prefix.$cluster.$hostname.service.system_swapping)"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries($prefix.$cluster.$hostname.service.client_connections)"
    }
   ]
  },
  {
   "title": "Average Migrations Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 6 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries($prefix.$cluster.$hostname.$namespace.migrate_rx_partitions_remaining)"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode($prefix.$cluster.$hostname.service.cluster_size, 2)"
    },
    {
     "target": "alias(sumSeries(pow(#A, 0)), 'Live Nodes')",
     "targetFull": "alias(sumSeries(pow(aliasByNode($prefix.$cluster.$hostname.service.cluster_size, 2), 0)), 'Live Nodes')"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries($prefix.$cluster.$hostname.service.fabric_connections), 'Fabric')"
    },
    {
     "target": "alias(sumSeries($prefix.$cluster.$hostname.service.heartbeat_connections), 'Heartbeat')"
    },
    {
     "target": "alias(sumSeries($prefix.$cluster.$hostname.service.client_connections), 'Client')"
    }
   ]
  },
  { "title": "Namespace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode($prefix.$cluster.$hostname.$namespace.objects, 3, 'sum')"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.memory_used_bytes, 3, 'sum'), '^', 'Total - ')"
    },
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.memory_used_index_bytes, 3, 'sum'), '^', 'Index - ')"
    },
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.memory_used_sindex_bytes, 3, 'sum'), '^', 'Sindex - ')"
    },
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.memory_used_data_bytes, 3, 'sum'), '^', 'Data - ')"
    }
   ]
  },
  {
   "title": "Migrate Partitions Remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.migrate_rx_partitions_remaining, 3, 'sum'), '^', 'Receive - ')"
    },
    {
     "target": "aliasSub(groupByNode($prefix.$cluster.$hostname.$namespace.migrate_tx_partitions_remaining, 3, 'sum'), '^', 'Transmit - ')"
    }
   ]
  },
  {
   "title": "Master Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode($prefix.$cluster.$hostname.$namespace.master_objects, 3, 'sum')"
    }
   ]
  },
  {
   "title": "Prole Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode($prefix.$cluster.$hostname.$namespace.prole_objects, 3, 'sum')"
    }
   ]
  },
  {
   "title": "Expired Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(derivative($prefix.$cluster.$hostname.$namespace.expired_objects), 3, 'sum')"
    }
   ]
  },
  {
   "title": "Evicted Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(derivative($prefix.$cluster.$hostname.$namespace.evicted_objects), 3, 'sum')"
    }
   ]
  },
  {
   "title": "Client Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_read_success), 3, 'sum'), '^', 'Success - ')"
    },
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_read_error), 3, 'sum'), '^', 'Error - ')"
    },
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_read_not_found), 3, 'sum'), '^', 'Not Found - ')"
    },
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_read_timeout), 3, 'sum'), '^', 'Timeout - ')"
    }
   ]
  },
  {
   "title": "Client Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_write_success), 3, 'sum'), '^', 'Success - ')"
    },
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_write_error), 3, 'sum'), '^', 'Error - ')"
    },
    {
     "target": "aliasSub(groupByNode(derivative($prefix.$cluster.$hostname.$namespace.client_write_timeout), 3, 'sum'), '^', 'Timeout - ')"
    }
   ]
  },
  {
   "title": "Device Available %",
   "type": "graph",
   "description": "Device available measures the contiguous disk space. In other words, this is Device Free - Fragmented space.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "groupByNode($prefix.$cluster.$hostname.$namespace.device_available_pct, 3, 'average')"
    }
   ]
  },
  {
   "title": "Device Free %",
   "type": "graph",
   "description": "Device free is the overall measure of free space on the disk. This does not take into account unusable space due to fragmentation.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "groupByNode($prefix.$cluster.$hostname.$namespace.device_free_pct, 3, 'average')"
    }
   ]
  },
  {
   "title": "HWM Breached",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode($prefix.$cluster.$hostname.$namespace.hwm_breached, 2, 3)"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode($prefix.$cluster.$hostname.$namespace.stop_writes, 2, 3)"
    }
   ]
  }
 ]
}